def getRelations():
    materiasDependencias = [
        {"materia": "Inglés I", "depende": "Inglés II", "cuatrimestreObjetivo": 2},
        {"materia": "Inglés II", "depende": "Inglés III", "cuatrimestreObjetivo": 3},
        {"materia": "Inglés III", "depende": "Inglés IV", "cuatrimestreObjetivo": 4},
        {"materia": "Inglés IV", "depende": "Inglés V", "cuatrimestreObjetivo": 5},
        {"materia": "Inglés V", "depende": "Inglés VI", "cuatrimestreObjetivo": 6},
        {"materia": "Inglés VI", "depende": "Inglés VII", "cuatrimestreObjetivo": 7},
        {"materia": "Inglés VII", "depende": "Inglés VIII", "cuatrimestreObjetivo": 8},
        {"materia": "Inglés VIII", "depende": "Inglés IX", "cuatrimestreObjetivo": 9},
        {"materia": "Desarrollo Humano y Valores", "depende": "Inteligencia Emocional y Manejo de Conflictos",
         "cuatrimestreObjetivo": 3},
        {"materia": "Programación para Móviles I", "depende": "Programación para Móviles II",
         "cuatrimestreObjetivo": 9},
        {"materia": "Programación para Móviles I", "depende": "Seguridad de la Información", "cuatrimestreObjetivo": 9},
        {"materia": "Cálculo Diferencial", "depende": "Cálculo Integral", "cuatrimestreObjetivo": 3},
        {"materia": "Cálculo Integral", "depende": "Matemáticas para Ingeniería I", "cuatrimestreObjetivo": 4},
        {"materia": "Matemáticas para Ingeniería I", "depende": "Matemáticas para Ingeniería II",
         "cuatrimestreObjetivo": 5},
        {"materia": "Probabilidad y Estadística", "depende": "Inteligencia Artificial", "cuatrimestreObjetivo": 8},
        {"materia": "Lenguajes y Autómatas", "depende": "Compiladores e Intérpretes", "cuatrimestreObjetivo": 8},

        {"materia": "Programación Orientada a Objetos", "depende": "Programación Visual", "cuatrimestreObjetivo": 3},
        {"materia": "Programación Visual", "depende": "Programación Web", "cuatrimestreObjetivo": 4},
        {"materia": "Programación Web", "depende": "Lenguajes y Autómatas", "cuatrimestreObjetivo": 7},
        {"materia": "Programación Web", "depende": "Programación Cliente Servidor", "cuatrimestreObjetivo": 5},
        {"materia": "Programación Cliente Servidor", "depende": "Sistemas Operativos", "cuatrimestreObjetivo": 7},
        {"materia": "Programación Cliente Servidor", "depende": "Programación Concurrente", "cuatrimestreObjetivo": 7},
        {"materia": "Programación Cliente Servidor", "depende": "Estancia I", "cuatrimestreObjetivo": 6},
        {"materia": "Sistemas Operativos", "depende": "Arquitectura Orientada a Servicios", "cuatrimestreObjetivo": 9},

        {"materia": "Algoritmos", "depende": "Programación Orientada a Objetos", "cuatrimestreObjetivo": 2},
        {"materia": "Algoritmos", "depende": "Estructura de Datos", "cuatrimestreObjetivo": 2},
        {"materia": "Estructura de Datos", "depende": "Estructura de Datos Avanzadas", "cuatrimestreObjetivo": 3},
        {"materia": "Diseño de Interfaces", "depende": "Minería de Datos", "cuatrimestreObjetivo": 9},
        {"materia": "Redes", "depende": "Sistemas Operativos", "cuatrimestreObjetivo": 7},
        {"materia": "Programación Concurrente", "depende": "Programación para Móviles I", "cuatrimestreObjetivo": 8},
        {"materia": "Programación Concurrente", "depende": "Arquitectura Orientada a Servicios",
         "cuatrimestreObjetivo": 9},
        {"materia": "Análisis Financiero de Software", "depende": "Administración de Proyectos de Software",
         "cuatrimestreObjetivo": 9},
        {"materia": "Matemáticas Discretas", "depende": "Inteligencia Artificial", "cuatrimestreObjetivo": 8},
        {"materia": "Fundamentos de Base de Datos", "depende": "Base de Datos", "cuatrimestreObjetivo": 4},
        {"materia": "Base de Datos", "depende": "Minería de Datos", "cuatrimestreObjetivo": 9},
        {"materia": "Arquitectura de Software", "depende": "Calidad del Software", "cuatrimestreObjetivo": 6},
        {"materia": "Calidad del Software", "depende": "Pruebas del Software", "cuatrimestreObjetivo": 7},
        {"materia": "Pruebas del Software", "depende": "Análisis Financiero de Software", "cuatrimestreObjetivo": 8},
        {"materia": "Pruebas del Software", "depende": "Mantenimiento de Software", "cuatrimestreObjetivo": 8},
        {"materia": "Expresión Oral y Escrita I", "depende": "Expresión Oral y Escrita II", "cuatrimestreObjetivo": 9},
        {"materia": "Procesos de Desarrollo de Software", "depende": "Ingeniería de Requerimientos de Software",
         "cuatrimestreObjetivo": 3},
        {"materia": "Ingeniería de Requerimientos de Software", "depende": "Arquitectura de Software",
         "cuatrimestreObjetivo": 5},
        {"materia": "Electricidad y Magnetismo", "depende": "Sistemas Digitales", "cuatrimestreObjetivo": 5},
        {"materia": "Sistemas Digitales", "depende": "Arquitectura de Computadoras", "cuatrimestreObjetivo": 6},
        {"materia": "Estancia I", "depende": "Estancia II", "cuatrimestreObjetivo": 7},
    ]

    return materiasDependencias